twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic : cmd_vel
        timeout: 0.5
        priority: 10
      keyboard:
        topic : cmd_vel_key
        timeout: 0.5
        priority: 90
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
